version: '3'

services:
  focalboard:
    image: mattermost/focalboard
    container_name: focalboard
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - 106:8000

volumes:
  data:
