version: '2'

services:
  mysqldata:
    image: mysql:5.7
    container_name: huginn.db.data
    command: /bin/true

  mysql:
    image: mysql:5.7
    container_name: huginn.db
    restart: always
    env_file:
      - ./mysql.env
    volumes_from:
      - mysqldata

  web:
    image: huginn/huginn-single-process
    container_name: huginn.web
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./mysql.env
      - ./secrets.env
    depends_on:
      - mysql

  threaded:
    image: huginn/huginn-single-process
    container_name: huginn.thread
    command: /scripts/init bin/threaded.rb
    restart: always
    env_file:
      - ./mysql.env
      - ./secrets.env
    depends_on:
      - mysql
      - web

