version: "3"

services:
  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser
    user: 0:0
    ports:
      - 9001:8080
    volumes:
      - /home/bhickta/Filebrowser/data:/data
      - /home/bhickta/Filebrowser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
