version: '3'
services: 
  wallabag: 
    container_name: wallabag 
    image: wallabag/wallabag 
    ports: 
    - 9880:80 
    environment: 
    - SYMFONY__ENV__DOMAIN_NAME=http://localhost:9880
    - SYMFONY__ENV__MAILER_HOST=email.domain 
    - SYMFONY__ENV__MAILER_USER=email@domain 
    - SYMFONY__ENV__MAILER_PASSWORD=pass 
    - SYMFONY__ENV__FROM_EMAIL=from@domain 
    volumes: 
    - data:/var/www/wallabag/data 
    - images:/var/www/wallabag/web/assets/images
volumes:
  data:
  images:
