version: '2.4'
services:
    archivebox:
        image: ${DOCKER_IMAGE:-archivebox/archivebox:master}
        container_name: archivebox.app
        command: server --quick-init 0.0.0.0:8000
        ports:
            - 8000:8000
        environment:
            - ALLOWED_HOSTS=*                   # add any config options you want as env vars
            - MEDIA_MAX_SIZE=750m
        volumes:
            - ./data:/data
